In [7]:
from CybORG import CybORG
from CybORG.Simulator.Scenarios import EnterpriseScenarioGenerator
from CybORG.Simulator.Actions import Sleep
from CybORG.Agents import SleepAgent, EnterpriseGreenAgent, FiniteStateRedAgent


In [8]:
sg = EnterpriseScenarioGenerator(blue_agent_class=SleepAgent, 
                                green_agent_class=EnterpriseGreenAgent, 
                                red_agent_class=SleepAgent)
cyborg = CybORG(scenario_generator=sg)

In [9]:
from CybORG.Agents.Wrappers import BlueFixedActionWrapper

env = BlueFixedActionWrapper(env=cyborg)
obs, _ = env.reset()

# optional pretty-printing
from rich import print

print("{} Blue agents: {}".format(len(obs.keys()),obs.keys()))
# for k in obs.keys():
#   print('{}'.format(k)) 
#   print(obs[k])
#   # print(env.action_space(k))
#   print(env.action_labels(k))

aBlueAgent = next(iter(obs))
print("Pertaining to: {}".format(aBlueAgent))
print("{} observations types: \n{}".format(len(obs[aBlueAgent].keys()),obs[aBlueAgent].keys()))
print("{} action labels: \n{}".format(env.action_space(aBlueAgent), env.action_labels(aBlueAgent)))



5 Blue agents: dict_keys(['blue_agent_0', 'blue_agent_1', 'blue_agent_2', 'blue_agent_3', 'blue_agent_4'])

Pertaining to: blue_agent_0

11 observations types: 
dict_keys(['success', 'restricted_zone_a_subnet_router', 'restricted_zone_a_subnet_user_host_0', 
'restricted_zone_a_subnet_user_host_1', 'restricted_zone_a_subnet_user_host_2', 
'restricted_zone_a_subnet_user_host_3', 'restricted_zone_a_subnet_user_host_4', 
'restricted_zone_a_subnet_user_host_5', 'restricted_zone_a_subnet_server_host_0', 
'restricted_zone_a_subnet_server_host_1', 'restricted_zone_a_subnet_server_host_2'])

Discrete(82) action labels: 
['Analyse restricted_zone_a_subnet_server_host_0', 'Analyse restricted_zone_a_subnet_server_host_1', 'Analyse 
restricted_zone_a_subnet_server_host_2', '[Invalid] Analyse restricted_zone_a_subnet_server_host_3', '[Invalid] 
Analyse restricted_zone_a_subnet_server_host_4', '[Invalid] Analyse restricted_zone_a_subnet_server_host_5', 
'Analyse restricted_zone_a_subnet_user_host_0', 'Analyse restricted_zone_a_subnet_user_host_1', 'Analyse 
restricted_zone_a_subnet_user_host_2', 'Analyse restricted_zone_a_subnet_user_host_3', 'Analyse 
restricted_zone_a_subnet_user_host_4', 'Analyse restricted_zone_a_subnet_user_host_5', '[Invalid] Analyse 
restricted_zone_a_subnet_user_host_6', '[Invalid] Analyse restricted_zone_a_subnet_user_host_7', '[Invalid] Analyse
restricted_zone_a_subnet_user_host_8', '[Invalid] Analyse restricted_zone_a_subnet_user_host_9', 'Monitor', 'Remove
restricted_zone_a_subnet_server_host_0', 'Remove restricted_zone_a_subnet_server_host_1', 'Remove 
restricted_zone_a_subnet_server_host_2', '[Invalid] Remove restricted_zone_a_subnet_server_host_3', '[Invalid] 
Remove restricted_zone_a_subnet_server_host_4', '[Invalid] Remove restricted_zone_a_subnet_server_host_5', 'Remove 
restricted_zone_a_subnet_user_host_0', 'Remove restricted_zone_a_subnet_user_host_1', 'Remove 
restricted_zone_a_subnet_user_host_2', 'Remove restricted_zone_a_subnet_user_host_3', 'Remove 
restricted_zone_a_subnet_user_host_4', 'Remove restricted_zone_a_subnet_user_host_5', '[Invalid] Remove 
restricted_zone_a_subnet_user_host_6', '[Invalid] Remove restricted_zone_a_subnet_user_host_7', '[Invalid] Remove 
restricted_zone_a_subnet_user_host_8', '[Invalid] Remove restricted_zone_a_subnet_user_host_9', 'Restore 
restricted_zone_a_subnet_server_host_0', 'Restore restricted_zone_a_subnet_server_host_1', 'Restore 
restricted_zone_a_subnet_server_host_2', '[Invalid] Restore restricted_zone_a_subnet_server_host_3', '[Invalid] 
Restore restricted_zone_a_subnet_server_host_4', '[Invalid] Restore restricted_zone_a_subnet_server_host_5', 
'Restore restricted_zone_a_subnet_user_host_0', 'Restore restricted_zone_a_subnet_user_host_1', 'Restore 
restricted_zone_a_subnet_user_host_2', 'Restore restricted_zone_a_subnet_user_host_3', 'Restore 
restricted_zone_a_subnet_user_host_4', 'Restore restricted_zone_a_subnet_user_host_5', '[Invalid] Restore 
restricted_zone_a_subnet_user_host_6', '[Invalid] Restore restricted_zone_a_subnet_user_host_7', '[Invalid] Restore
restricted_zone_a_subnet_user_host_8', '[Invalid] Restore restricted_zone_a_subnet_user_host_9', 'Sleep', 
'AllowTrafficZone restricted_zone_a_subnet (10.0.60.0/24) <- admin_network_subnet (10.0.8.0/24)', 'AllowTrafficZone
restricted_zone_a_subnet (10.0.60.0/24) <- contractor_network_subnet (10.0.213.0/24)', 'AllowTrafficZone 
restricted_zone_a_subnet (10.0.60.0/24) <- internet_subnet (10.0.117.0/24)', 'AllowTrafficZone 
restricted_zone_a_subnet (10.0.60.0/24) <- office_network_subnet (10.0.150.0/24)', 'AllowTrafficZone 
restricted_zone_a_subnet (10.0.60.0/24) <- operational_zone_a_subnet (10.0.166.0/24)', 'AllowTrafficZone 
restricted_zone_a_subnet (10.0.60.0/24) <- operational_zone_b_subnet (10.0.178.0/24)', 'AllowTrafficZone 
restricted_zone_a_subnet (10.0.60.0/24) <- public_access_zone_subnet (10.0.220.0/24)', 'AllowTrafficZone 
restricted_zone_a_subnet (10.0.60.0/24) <- restricted_zone_b_subnet (10.0.90.0/24)', 'BlockTrafficZone 
restricted_zone_a_subnet (10.0.60.0/24) <- admin_network_subnet (10.0.8.0/24)', 'BlockTrafficZone 
restricted_zone_a_subnet (10.0.60.0/24) <- contractor_network_subnet (10.0.213.0/24)', 'BlockTrafficZone 
restricted_zone_a_subnet (10.0.60.0/24) <- internet_subnet (10.0.117.0/24)', 'BlockTrafficZone 
restricted_zone_a_subnet (10.0.60.0/24) <- office_network_subnet (10.0.150.0/24)', 'BlockTrafficZone 
restricted_zone_a_subnet (10.0.60.0/24) <- operational_zone_a_subnet (10.0.166.0/24)', 'BlockTrafficZone 
restricted_zone_a_subnet (10.0.60.0/24) <- o

In [10]:
action_index = 42
actions = {aBlueAgent: action_index} # 'Restore restricted_zone_a_subnet_user_host_3'
obs, reward, terminated, truncated, info = env.step(actions)
print("{} action {}: {}".format(aBlueAgent,action_index, env.action_labels(aBlueAgent)[action_index]))
print("{} reward: {}".format(aBlueAgent, reward[aBlueAgent]))
# env.action_labels(aBlueAgent)[action_index]

blue_agent_0 action 42: Restore restricted_zone_a_subnet_user_host_3

blue_agent_0 reward: -1

In [11]:
import numpy as np
messages = {'blue_agent_0': np.array([1, 1, 0, 0, 0, 0, 0, 0]), 
            # 'blue_agent_1': np.array([1, 0, 0, 0, 0, 0, 0, 0]),
            # 'blue_agent_2': np.array([1, 0, 0, 0, 0, 0, 0, 0]),
            'blue_agent_3': np.array([1, 0, 0, 0, 0, 0, 0, 0])}
obs, reward, terminated, truncated, info = env.step(actions, messages=messages)
print(obs['blue_agent_0'])


{
    'success': <TernaryEnum.IN_PROGRESS: 4>,
    'message': [
        array([False, False, False, False, False, False, False, False]),
        array([False, False, False, False, False, False, False, False]),
        array([ True, False, False, False, False, False, False, False]),
        array([False, False, False, False, False, False, False, False])
    ]
}

In [12]:
reset = cyborg.reset(agent=aBlueAgent)
initial_obs = reset.observation

print("\nBlue Agent 0: Initial Observation")
print("\nKeys Only: \n")
print(initial_obs.keys())

Blue Agent 0: Initial Observation

Keys Only:

dict_keys(['success', 'restricted_zone_a_subnet_router', 'restricted_zone_a_subnet_user_host_0', 
'restricted_zone_a_subnet_user_host_1', 'restricted_zone_a_subnet_user_host_2', 
'restricted_zone_a_subnet_user_host_3', 'restricted_zone_a_subnet_user_host_4', 
'restricted_zone_a_subnet_user_host_5', 'restricted_zone_a_subnet_user_host_6', 
'restricted_zone_a_subnet_user_host_7', 'restricted_zone_a_subnet_user_host_8', 
'restricted_zone_a_subnet_server_host_0'])

In [13]:
host=list(initial_obs.keys())[2]
print("\nSingle Host: {}".format(host))
print(initial_obs[host])


Single Host: restricted_zone_a_subnet_user_host_0

{
    'Interface': [
        {
            'interface_name': 'eth0',
            'ip_address': IPv4Address('10.0.216.184'),
            'Subnet': IPv4Network('10.0.216.0/24')
        }
    ],
    'Sessions': [
        {
            'session_id': 0,
            'username': 'ubuntu',
            'timeout': 0,
            'PID': 6949,
            'Type': <SessionType.VELOCIRAPTOR_SERVER: 8>,
            'agent': 'blue_agent_0'
        }
    ],
    'Processes': [{'PID': 6949, 'username': 'ubuntu'}],
    'User Info': [{'username': 'root', 'Groups': [{'GID': 0}]}, {'username': 'user', 'Groups': [{'GID': 1}]}],
    'System info': {
        'Hostname': 'restricted_zone_a_subnet_user_host_0',
        'OSType': <OperatingSystemType.LINUX: 3>,
        'OSDistribution': <OperatingSystemDistribution.KALI: 9>,
        'OSVersion': <OperatingSystemVersion.K2019_4: 11>,
        'Architecture': <Architecture.x64: 2>,
        'position': array([0., 0.])
    }
}

In [14]:

obs_1 = cyborg.step(agent=aBlueAgent, action=Sleep()).observation

print("\n{}: Step #1".format(aBlueAgent))
print(obs_1)

blue_agent_0: Step #1

{
    'success': <TernaryEnum.UNKNOWN: 2>,
    'action': Sleep,
    'restricted_zone_a_subnet_user_host_6': {
        'Processes': [{'Connections': [{'local_port': 55530, 'local_address': IPv4Address('10.0.216.100')}]}],
        'Interface': [{'ip_address': IPv4Address('10.0.216.100')}],
        'System info': {
            'Hostname': 'restricted_zone_a_subnet_user_host_6',
            'OSType': <OperatingSystemType.LINUX: 3>,
            'OSDistribution': <OperatingSystemDistribution.UBUNTU: 8>,
            'OSVersion': <OperatingSystemVersion.UNKNOWN: 1>,
            'Architecture': <Architecture.x64: 2>,
            'position': array([0., 0.])
        }
    }
}

In [15]:
for agent_name, ai in cyborg.environment_controller.agent_interfaces.items():
    # print("{}:{}".format(agent_name, ai))
    if 'green' in agent_name and isinstance(ai.agent, EnterpriseGreenAgent):
        ai.agent.fp_detection_rate = 1.0

obs_2 = cyborg.step(agent='blue_agent_0', action=Sleep()).observation

print("\nBlue Agent 0: Step #2 with Green False Positive \n")
print(obs_2)

Blue Agent 0: Step #2 with Green False Positive

{
    'success': <TernaryEnum.UNKNOWN: 2>,
    'action': Sleep,
    'restricted_zone_a_subnet_user_host_1': {
        'Processes': [{'Connections': [{'local_port': 58110, 'local_address': IPv4Address('10.0.216.226')}]}],
        'Interface': [{'ip_address': IPv4Address('10.0.216.226')}],
        'System info': {
            'Hostname': 'restricted_zone_a_subnet_user_host_1',
            'OSType': <OperatingSystemType.LINUX: 3>,
            'OSDistribution': <OperatingSystemDistribution.KALI: 9>,
            'OSVersion': <OperatingSystemVersion.K2019_4: 11>,
            'Architecture': <Architecture.x64: 2>,
            'position': array([0., 0.])
        }
    },
    'restricted_zone_a_subnet_user_host_3': {
        'Processes': [{'Connections': [{'local_port': 56638, 'local_address': IPv4Address('10.0.216.160')}]}],
        'Interface': [{'ip_address': IPv4Address('10.0.216.160')}],
        'System info': {
            'Hostname': 'restricted_zone_a_subnet_user_host_3',
            'OSType': <OperatingSystemType.LINUX: 3>,
            'OSDistribution': <OperatingSystemDistribution.KALI: 9>,
            'OSVersion': <OperatingSystemVersion.K2019_4: 11>,
            'Architecture': <Architecture.x64: 2>,
            'position': array([0., 0.])
        }
    },
    'restricted_zone_a_subnet_user_host_5': {
        'Processes': [{'Connections': [{'local_port': 56979, 'local_address': IPv4Address('10.0.216.53')}]}],
        'Interface': [{'ip_address': IPv4Address('10.0.216.53')}],
        'System info': {
            'Hostname': 'restricted_zone_a_subnet_user_host_5',
            'OSType': <OperatingSystemType.LINUX: 3>,
            'OSDistribution': <OperatingSystemDistribution.KALI: 9>,
            'OSVersion': <OperatingSystemVersion.K2019_4: 11>,
            'Architecture': <Architecture.x64: 2>,
            'position': array([0., 0.])
        }
    },
    'restricted_zone_a_subnet_server_host_0': {
        'Processes': [
            {
                'Connections': [
                    {
                        'remote_port': 58802,
                        'local_address': IPv4Address('10.0.0.229'),
                        'remote_address': IPv4Address('10.0.216.254')
                    }
                ]
            },
            {
                'Connections': [
                    {
                        'remote_port': 50830,
                        'local_address': IPv4Address('10.0.0.153'),
                        'remote_address': IPv4Address('10.0.216.254')
                    }
                ]
            }
        ],
        'Interface': [{'ip_address': IPv4Address('10.0.0.229')}, {'ip_address': IPv4Address('10.0.0.153')}],
        'System info': {
            'Hostname': 'restricted_zone_a_subnet_server_host_0',
            'OSType': <OperatingSystemType.LINUX: 3>,
            'OSDistribution': <OperatingSystemDistribution.KALI: 9>,
            'OSVersion': <OperatingSystemVersion.K2019_4: 11>,
            'Architecture': <Architecture.x64: 2>,
            'position': array([0., 0.])
        }
    }
}